package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dangnhap generated by hbm2java
 */
@Entity
@Table(name = "dangnhap", catalog = "detainckh")
public class Dangnhap implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String email;
	private String uname;
	private String pass;
	private String quyen;

	public Dangnhap() {
	}

	public Dangnhap(String uname, String pass, String quyen) {
		this.uname = uname;
		this.pass = pass;
		this.quyen = quyen;
	}

	public Dangnhap(String fullName, String email, String uname, String pass, String quyen) {
		this.fullName = fullName;
		this.email = email;
		this.uname = uname;
		this.pass = pass;
		this.quyen = quyen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FullName", length = 50)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "uName", nullable = false, length = 45)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "Pass", nullable = false, length = 45)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "Quyen", nullable = false, length = 45)
	public String getQuyen() {
		return this.quyen;
	}

	public void setQuyen(String quyen) {
		this.quyen = quyen;
	}

}
