package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetaiNoidungnc generated by hbm2java
 */
@Entity
@Table(name = "detai_noidungnc", catalog = "detainckh")
public class DetaiNoidungnc implements java.io.Serializable {

	private String stt;
	private Detai detai;
	private String noidungcv;
	private String sanphamphaidat;
	private String thoigian;
	private String nguoithuchien;

	public DetaiNoidungnc() {
	}

	public DetaiNoidungnc(String stt) {
		this.stt = stt;
	}

	public DetaiNoidungnc(String stt, Detai detai, String noidungcv, String sanphamphaidat, String thoigian,
			String nguoithuchien) {
		this.stt = stt;
		this.detai = detai;
		this.noidungcv = noidungcv;
		this.sanphamphaidat = sanphamphaidat;
		this.thoigian = thoigian;
		this.nguoithuchien = nguoithuchien;
	}

	@Id

	@Column(name = "stt", unique = true, nullable = false)
	public String getStt() {
		return this.stt;
	}

	public void setStt(String stt) {
		this.stt = stt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai")
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@Column(name = "noidungcv")
	public String getNoidungcv() {
		return this.noidungcv;
	}

	public void setNoidungcv(String noidungcv) {
		this.noidungcv = noidungcv;
	}

	@Column(name = "sanphamphaidat")
	public String getSanphamphaidat() {
		return this.sanphamphaidat;
	}

	public void setSanphamphaidat(String sanphamphaidat) {
		this.sanphamphaidat = sanphamphaidat;
	}

	@Column(name = "thoigian")
	public String getThoigian() {
		return this.thoigian;
	}

	public void setThoigian(String thoigian) {
		this.thoigian = thoigian;
	}

	@Column(name = "nguoithuchien")
	public String getNguoithuchien() {
		return this.nguoithuchien;
	}

	public void setNguoithuchien(String nguoithuchien) {
		this.nguoithuchien = nguoithuchien;
	}

}
