package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetaiSinhvienId generated by hbm2java
 */
@Embeddable
public class DetaiSinhvienId implements java.io.Serializable {

	private String maDeTai;
	private String mssv;
	private String trangThai;
	private String maCapDt;

	public DetaiSinhvienId() {
	}

	public DetaiSinhvienId(String maDeTai, String mssv, String trangThai, String maCapDt) {
		this.maDeTai = maDeTai;
		this.mssv = mssv;
		this.trangThai = trangThai;
		this.maCapDt = maCapDt;
	}

	@Column(name = "MaDeTai")
	public String getMaDeTai() {
		return this.maDeTai;
	}

	public void setMaDeTai(String maDeTai) {
		this.maDeTai = maDeTai;
	}

	@Column(name = "MSSV", length = 50)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "TrangThai")
	public String getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(String trangThai) {
		this.trangThai = trangThai;
	}

	@Column(name = "MaCapDT", unique = true)
	public String getMaCapDt() {
		return this.maCapDt;
	}

	public void setMaCapDt(String maCapDt) {
		this.maCapDt = maCapDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetaiSinhvienId))
			return false;
		DetaiSinhvienId castOther = (DetaiSinhvienId) other;

		return ((this.getMaDeTai() == castOther.getMaDeTai()) || (this.getMaDeTai() != null
				&& castOther.getMaDeTai() != null && this.getMaDeTai().equals(castOther.getMaDeTai())))
				&& ((this.getMssv() == castOther.getMssv()) || (this.getMssv() != null && castOther.getMssv() != null
						&& this.getMssv().equals(castOther.getMssv())))
				&& ((this.getTrangThai() == castOther.getTrangThai()) || (this.getTrangThai() != null
						&& castOther.getTrangThai() != null && this.getTrangThai().equals(castOther.getTrangThai())))
				&& ((this.getMaCapDt() == castOther.getMaCapDt()) || (this.getMaCapDt() != null
						&& castOther.getMaCapDt() != null && this.getMaCapDt().equals(castOther.getMaCapDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaDeTai() == null ? 0 : this.getMaDeTai().hashCode());
		result = 37 * result + (getMssv() == null ? 0 : this.getMssv().hashCode());
		result = 37 * result + (getTrangThai() == null ? 0 : this.getTrangThai().hashCode());
		result = 37 * result + (getMaCapDt() == null ? 0 : this.getMaCapDt().hashCode());
		return result;
	}

}
