package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DetaiSinhvien generated by hbm2java
 */
@Entity
@Table(name = "detai_sinhvien", catalog = "detainckh", uniqueConstraints = @UniqueConstraint(columnNames = "MaCapDT"))
public class DetaiSinhvien implements java.io.Serializable {

	private DetaiSinhvienId id;
	private Detai detai;
	private Thongtinsinhvien thongtinsinhvien;

	public DetaiSinhvien() {
	}

	public DetaiSinhvien(DetaiSinhvienId id) {
		this.id = id;
	}

	public DetaiSinhvien(DetaiSinhvienId id, Detai detai, Thongtinsinhvien thongtinsinhvien) {
		this.id = id;
		this.detai = detai;
		this.thongtinsinhvien = thongtinsinhvien;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDeTai", column = @Column(name = "MaDeTai")),
			@AttributeOverride(name = "mssv", column = @Column(name = "MSSV", length = 50)),
			@AttributeOverride(name = "trangThai", column = @Column(name = "TrangThai")),
			@AttributeOverride(name = "maCapDt", column = @Column(name = "MaCapDT", unique = true)) })
	public DetaiSinhvienId getId() {
		return this.id;
	}

	public void setId(DetaiSinhvienId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai", insertable = false, updatable = false)
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSSV", insertable = false, updatable = false)
	public Thongtinsinhvien getThongtinsinhvien() {
		return this.thongtinsinhvien;
	}

	public void setThongtinsinhvien(Thongtinsinhvien thongtinsinhvien) {
		this.thongtinsinhvien = thongtinsinhvien;
	}

}
