package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetaiSanpham generated by hbm2java
 */
@Entity
@Table(name = "detai_sanpham", catalog = "detainckh")
public class DetaiSanpham implements java.io.Serializable {

	private String stt;
	private Detai detai;
	private String tenSp;
	private String soLuong;
	private String yeuCauKhoaHoc;

	public DetaiSanpham() {
	}

	public DetaiSanpham(String stt) {
		this.stt = stt;
	}

	public DetaiSanpham(String stt, Detai detai, String tenSp, String soLuong, String yeuCauKhoaHoc) {
		this.stt = stt;
		this.detai = detai;
		this.tenSp = tenSp;
		this.soLuong = soLuong;
		this.yeuCauKhoaHoc = yeuCauKhoaHoc;
	}

	@Id

	@Column(name = "stt", unique = true, nullable = false)
	public String getStt() {
		return this.stt;
	}

	public void setStt(String stt) {
		this.stt = stt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai")
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@Column(name = "TenSp")
	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	@Column(name = "SoLuong")
	public String getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(String soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "YeuCauKhoaHoc")
	public String getYeuCauKhoaHoc() {
		return this.yeuCauKhoaHoc;
	}

	public void setYeuCauKhoaHoc(String yeuCauKhoaHoc) {
		this.yeuCauKhoaHoc = yeuCauKhoaHoc;
	}

}
