package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Diemdanhgia generated by hbm2java
 */
@Entity
@Table(name = "diemdanhgia", catalog = "detainckh")
public class Diemdanhgia implements java.io.Serializable {

	private DiemdanhgiaId id;
	private Detai detai;
	private Thongtincanbo thongtincanbo;

	public Diemdanhgia() {
	}

	public Diemdanhgia(DiemdanhgiaId id, Thongtincanbo thongtincanbo) {
		this.id = id;
		this.thongtincanbo = thongtincanbo;
	}

	public Diemdanhgia(DiemdanhgiaId id, Detai detai, Thongtincanbo thongtincanbo) {
		this.id = id;
		this.detai = detai;
		this.thongtincanbo = thongtincanbo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDeTai", column = @Column(name = "MaDeTai")),
			@AttributeOverride(name = "tinhHinhNhienCuu", column = @Column(name = "TinhHinhNhienCuu")),
			@AttributeOverride(name = "mucTieu", column = @Column(name = "MucTieu")),
			@AttributeOverride(name = "phuongPhap", column = @Column(name = "PhuongPhap")),
			@AttributeOverride(name = "gd", column = @Column(name = "GD")),
			@AttributeOverride(name = "khaNangPhatTrien", column = @Column(name = "KhaNangPhatTrien")),
			@AttributeOverride(name = "tongDiem", column = @Column(name = "TongDiem")),
			@AttributeOverride(name = "maGv", column = @Column(name = "MaGV", nullable = false, length = 50)) })
	public DiemdanhgiaId getId() {
		return this.id;
	}

	public void setId(DiemdanhgiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai", insertable = false, updatable = false)
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGV", nullable = false, insertable = false, updatable = false)
	public Thongtincanbo getThongtincanbo() {
		return this.thongtincanbo;
	}

	public void setThongtincanbo(Thongtincanbo thongtincanbo) {
		this.thongtincanbo = thongtincanbo;
	}

}
