package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Filenckh generated by hbm2java
 */
@Entity
@Table(name = "filenckh", catalog = "detainckh")
public class Filenckh implements java.io.Serializable {

	private int id;
	private String fileName;
	private byte[] fileData;
	private String description;

	public Filenckh() {
	}

	public Filenckh(int id, String fileName, byte[] fileData) {
		this.id = id;
		this.fileName = fileName;
		this.fileData = fileData;
	}

	public Filenckh(int id, String fileName, byte[] fileData, String description) {
		this.id = id;
		this.fileName = fileName;
		this.fileData = fileData;
		this.description = description;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "FILE_NAME", nullable = false, length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_DATA", nullable = false)
	public byte[] getFileData() {
		return this.fileData;
	}

	public void setFileData(byte[] fileData) {
		this.fileData = fileData;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
