package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Importfileexcel generated by hbm2java
 */
@Entity
@Table(name = "importfileexcel", catalog = "detainckh")
public class Importfileexcel implements java.io.Serializable {

	private String id;
	private String ten;
	private String email;

	public Importfileexcel() {
	}

	public Importfileexcel(String id) {
		this.id = id;
	}

	public Importfileexcel(String id, String ten, String email) {
		this.id = id;
		this.ten = ten;
		this.email = email;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 250)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ten", length = 250)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "email", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
