package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Kinhphi generated by hbm2java
 */
@Entity
@Table(name = "kinhphi", catalog = "detainckh")
public class Kinhphi implements java.io.Serializable {

	private String stt;
	private Detai detai;
	private String congvien;
	private String thanhtien;
	private String ghichu;

	public Kinhphi() {
	}

	public Kinhphi(String stt) {
		this.stt = stt;
	}

	public Kinhphi(String stt, Detai detai, String congvien, String thanhtien, String ghichu) {
		this.stt = stt;
		this.detai = detai;
		this.congvien = congvien;
		this.thanhtien = thanhtien;
		this.ghichu = ghichu;
	}

	@Id

	@Column(name = "stt", unique = true, nullable = false)
	public String getStt() {
		return this.stt;
	}

	public void setStt(String stt) {
		this.stt = stt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai")
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@Column(name = "congvien")
	public String getCongvien() {
		return this.congvien;
	}

	public void setCongvien(String congvien) {
		this.congvien = congvien;
	}

	@Column(name = "thanhtien")
	public String getThanhtien() {
		return this.thanhtien;
	}

	public void setThanhtien(String thanhtien) {
		this.thanhtien = thanhtien;
	}

	@Column(name = "ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
