package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhancongnghiemthuId generated by hbm2java
 */
@Embeddable
public class PhancongnghiemthuId implements java.io.Serializable {

	private String maDeTai;
	private String maCanBo;

	public PhancongnghiemthuId() {
	}

	public PhancongnghiemthuId(String maDeTai, String maCanBo) {
		this.maDeTai = maDeTai;
		this.maCanBo = maCanBo;
	}

	@Column(name = "MaDeTai", nullable = false)
	public String getMaDeTai() {
		return this.maDeTai;
	}

	public void setMaDeTai(String maDeTai) {
		this.maDeTai = maDeTai;
	}

	@Column(name = "MaCanBo", nullable = false, length = 50)
	public String getMaCanBo() {
		return this.maCanBo;
	}

	public void setMaCanBo(String maCanBo) {
		this.maCanBo = maCanBo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhancongnghiemthuId))
			return false;
		PhancongnghiemthuId castOther = (PhancongnghiemthuId) other;

		return ((this.getMaDeTai() == castOther.getMaDeTai()) || (this.getMaDeTai() != null
				&& castOther.getMaDeTai() != null && this.getMaDeTai().equals(castOther.getMaDeTai())))
				&& ((this.getMaCanBo() == castOther.getMaCanBo()) || (this.getMaCanBo() != null
						&& castOther.getMaCanBo() != null && this.getMaCanBo().equals(castOther.getMaCanBo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaDeTai() == null ? 0 : this.getMaDeTai().hashCode());
		result = 37 * result + (getMaCanBo() == null ? 0 : this.getMaCanBo().hashCode());
		return result;
	}

}
