package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegisterId generated by hbm2java
 */
@Embeddable
public class RegisterId implements java.io.Serializable {

	private Integer sno;
	private String firstname;
	private String lastname;
	private String username;
	private String email;
	private String country;

	public RegisterId() {
	}

	public RegisterId(Integer sno, String firstname, String lastname, String username, String email, String country) {
		this.sno = sno;
		this.firstname = firstname;
		this.lastname = lastname;
		this.username = username;
		this.email = email;
		this.country = country;
	}

	@Column(name = "SNo")
	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "Username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegisterId))
			return false;
		RegisterId castOther = (RegisterId) other;

		return ((this.getSno() == castOther.getSno())
				|| (this.getSno() != null && castOther.getSno() != null && this.getSno().equals(castOther.getSno())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this.getFirstname() != null
						&& castOther.getFirstname() != null && this.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getLastname() == castOther.getLastname()) || (this.getLastname() != null
						&& castOther.getLastname() != null && this.getLastname().equals(castOther.getLastname())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSno() == null ? 0 : this.getSno().hashCode());
		result = 37 * result + (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37 * result + (getLastname() == null ? 0 : this.getLastname().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		return result;
	}

}
