package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thongtinsinhvien generated by hbm2java
 */
@Entity
@Table(name = "thongtinsinhvien", catalog = "detainckh")
public class Thongtinsinhvien implements java.io.Serializable {

	private String mssv;
	private String hoTen;
	private String email;
	private String sdt;
	private String khoa;
	private String lop;
	private String nganh;
	private String nienKhoa;
	private String ngaySinh;
	private String gioiTinh;
	private String cmnd;
	private String diaChi;
	private String tknganHang;
	private String chiNhanh;
	private Set<DetaiSinhvien> detaiSinhviens = new HashSet<DetaiSinhvien>(0);

	public Thongtinsinhvien() {
	}

	public Thongtinsinhvien(String mssv) {
		this.mssv = mssv;
	}

	public Thongtinsinhvien(String mssv, String hoTen, String email, String sdt, String khoa, String lop, String nganh,
			String nienKhoa, String ngaySinh, String gioiTinh, String cmnd, String diaChi, String tknganHang,
			String chiNhanh, Set<DetaiSinhvien> detaiSinhviens) {
		this.mssv = mssv;
		this.hoTen = hoTen;
		this.email = email;
		this.sdt = sdt;
		this.khoa = khoa;
		this.lop = lop;
		this.nganh = nganh;
		this.nienKhoa = nienKhoa;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.cmnd = cmnd;
		this.diaChi = diaChi;
		this.tknganHang = tknganHang;
		this.chiNhanh = chiNhanh;
		this.detaiSinhviens = detaiSinhviens;
	}

	@Id

	@Column(name = "MSSV", unique = true, nullable = false, length = 50)
	public String getMssv() {
		return this.mssv;
	}

	public void setMssv(String mssv) {
		this.mssv = mssv;
	}

	@Column(name = "HoTen", length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SDT", length = 50)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Khoa", length = 50)
	public String getKhoa() {
		return this.khoa;
	}

	public void setKhoa(String khoa) {
		this.khoa = khoa;
	}

	@Column(name = "Lop", length = 50)
	public String getLop() {
		return this.lop;
	}

	public void setLop(String lop) {
		this.lop = lop;
	}

	@Column(name = "Nganh", length = 50)
	public String getNganh() {
		return this.nganh;
	}

	public void setNganh(String nganh) {
		this.nganh = nganh;
	}

	@Column(name = "NienKhoa", length = 50)
	public String getNienKhoa() {
		return this.nienKhoa;
	}

	public void setNienKhoa(String nienKhoa) {
		this.nienKhoa = nienKhoa;
	}

	@Column(name = "NgaySinh", length = 50)
	public String getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(String ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh", length = 50)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "CMND", length = 50)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "DiaChi", length = 50)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "TKNganHang", length = 50)
	public String getTknganHang() {
		return this.tknganHang;
	}

	public void setTknganHang(String tknganHang) {
		this.tknganHang = tknganHang;
	}

	@Column(name = "ChiNhanh", length = 50)
	public String getChiNhanh() {
		return this.chiNhanh;
	}

	public void setChiNhanh(String chiNhanh) {
		this.chiNhanh = chiNhanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thongtinsinhvien")
	public Set<DetaiSinhvien> getDetaiSinhviens() {
		return this.detaiSinhviens;
	}

	public void setDetaiSinhviens(Set<DetaiSinhvien> detaiSinhviens) {
		this.detaiSinhviens = detaiSinhviens;
	}

}
