package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ykiendanhgia generated by hbm2java
 */
@Entity
@Table(name = "ykiendanhgia", catalog = "detainckh")
public class Ykiendanhgia implements java.io.Serializable {

	private YkiendanhgiaId id;
	private Detai detai;
	private String noiDung;

	public Ykiendanhgia() {
	}

	public Ykiendanhgia(YkiendanhgiaId id, Detai detai) {
		this.id = id;
		this.detai = detai;
	}

	public Ykiendanhgia(YkiendanhgiaId id, Detai detai, String noiDung) {
		this.id = id;
		this.detai = detai;
		this.noiDung = noiDung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maYkien", column = @Column(name = "MaYKien", nullable = false)),
			@AttributeOverride(name = "maDeTai", column = @Column(name = "MaDeTai", nullable = false, length = 50)) })
	public YkiendanhgiaId getId() {
		return this.id;
	}

	public void setId(YkiendanhgiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDeTai", nullable = false, insertable = false, updatable = false)
	public Detai getDetai() {
		return this.detai;
	}

	public void setDetai(Detai detai) {
		this.detai = detai;
	}

	@Column(name = "NoiDung", length = 3000)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
