package entities;
// Generated Dec 21, 2016 10:56:54 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YkiendanhgiaId generated by hbm2java
 */
@Embeddable
public class YkiendanhgiaId implements java.io.Serializable {

	private int maYkien;
	private String maDeTai;

	public YkiendanhgiaId() {
	}

	public YkiendanhgiaId(int maYkien, String maDeTai) {
		this.maYkien = maYkien;
		this.maDeTai = maDeTai;
	}

	@Column(name = "MaYKien", nullable = false)
	public int getMaYkien() {
		return this.maYkien;
	}

	public void setMaYkien(int maYkien) {
		this.maYkien = maYkien;
	}

	@Column(name = "MaDeTai", nullable = false, length = 50)
	public String getMaDeTai() {
		return this.maDeTai;
	}

	public void setMaDeTai(String maDeTai) {
		this.maDeTai = maDeTai;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YkiendanhgiaId))
			return false;
		YkiendanhgiaId castOther = (YkiendanhgiaId) other;

		return (this.getMaYkien() == castOther.getMaYkien())
				&& ((this.getMaDeTai() == castOther.getMaDeTai()) || (this.getMaDeTai() != null
						&& castOther.getMaDeTai() != null && this.getMaDeTai().equals(castOther.getMaDeTai())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaYkien();
		result = 37 * result + (getMaDeTai() == null ? 0 : this.getMaDeTai().hashCode());
		return result;
	}

}
